# Generated by Django 2.2.12 on 2021-03-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0002_auto_20210322_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
