# Generated by Django 2.2.12 on 2021-03-30 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workingApp', '0003_remove_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'userKey',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='list_key',
        ),
        migrations.AddField(
            model_name='task',
            name='completionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Task_list',
        ),
        migrations.AddField(
            model_name='task',
            name='listKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workingApp.TaskList'),
        ),
    ]
