# Generated by Django 2.2.12 on 2021-04-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0004_auto_20210330_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='listKey',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='workingApp.TaskList'),
            preserve_default=False,
        ),
    ]
