# Generated by Django 3.1.7 on 2021-04-21 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0005_auto_20210401_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='completionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
