# Generated by Django 3.2 on 2021-04-22 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0006_auto_20210421_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
